# Generated by Django 5.2.6 on 2025-10-08 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='conferenece',
            new_name='conference',
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ce champ ne doit contenir que des lettres', regex='^[a-zA-Z\\s-]+$')]),
        ),
    ]
