# Generated by Django 5.2.6 on 2025-10-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='confereence',
            new_name='conference',
        ),
    ]
