# Generated by Django 5.0 on 2025-10-24 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionapp', '0002_rename_confereence_session_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='le nom de la salle ne contient que des lettres et chiffres', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
