<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-26 11:01
=======
# Generated by Django 5.2.6 on 2025-09-26 11:08
>>>>>>> df5daa56f74cd80f69add844502b78735ab8bc6a

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('theme', models.CharField(choices=[('IA', 'Computer science & ia'), ('SE', 'Science & eng'), ('SC', 'Social sciences')], max_length=255)),
=======
>>>>>>> df5daa56f74cd80f69add844502b78735ab8bc6a
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
<<<<<<< HEAD
                ('submission_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField()),
                ('paper', models.FileField(upload_to='papers/')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('under review', 'under review'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=50)),
                ('payed', models.BooleanField(default=False)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ConferenceApp.conference')),
=======
                ('Submission_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField()),
                ('paper', models.FileField(upload_to='paper/')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('under review', 'under review'), ('submitted', 'submitted'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=50)),
                ('payed', models.BooleanField(default=False)),
                ('Submission_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('Conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ConferenceApp.conference')),
>>>>>>> df5daa56f74cd80f69add844502b78735ab8bc6a
            ],
        ),
    ]
