# Generated by Django 5.0 on 2025-10-10 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='desciption',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, 'la description doit contenir au moins 30 caractéres')]),
        ),
    ]
