# Generated by Django 5.2.6 on 2025-10-09 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, message='La description doit contenir au moins 30 caracteres.')]),
        ),
    ]
