# Generated by Django 5.2.6 on 2025-10-10 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='theme',
            field=models.CharField(choices=[('IA', 'Computer science & ia'), ('SE', 'Science & Engineering'), ('SC', 'Social Sciences & Education'), ('IT', 'Interdisciplinary Themes.')], default='IA', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, message='Vous devez saisir au moins 30 caractères')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ce champ ne doit contenir que des lettres', regex='^[a-zA-Z\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='paper/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('under review', 'under review'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=50),
        ),
    ]
