# Generated by Django 5.0 on 2025-10-24 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceapp', '0003_alter_conference_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='le titre doit contenir uniquement des lettres et espaces', regex='^[a-zA-Z\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.TextField(help_text='Séparez les mots-clés par des virgules (ex : IA, données, santé)', max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF (.pdf) sont autorisés.')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
